config/routes.rb
Movies::Application.routes.draw do

  get "users/new"
  get "users/welcome"
  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :trades

  resources :credit_items

  resources :credits

  resources :users

  resources :sessions

  resources :orders

  resources :credit_items

  resources :carts

  resources :line_items

  resources :products

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  get "store/used"
  get "store/most_wanted"
  get "store/thanks"
  get "store/join"

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

   root :to => "store", :action => "index"

  root to: 'store#index', as: 'store'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessible :email, :hashed_password, :password, :credit_available
  attr_accessor :password
  before_save :encrypt_password

  has_many :products
  has_many :credits
  has_many :orders
  has_many :trades

  validates :email,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}

  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true

  def add_credit_total_from_credit(credit)
    credit.credit_total.each do |request|
      request.user_id = nil
       credit_total << request
      end
    end


  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password + "ruby_rocks" + self.salt)
  end

  protected
  def encrypt_password
    return if password.blank?
    salt = generate_salt
    self.hashed_password = encrypt(password + "ruby_rocks" + self.salt)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end

  def generate_salt
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salt = ""
    1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
    self.salt = salt
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :is_admin?

  def index
    #@users = User.all
    @users = User.find(:all)
    @products = Product.where(wanted: 'yes')
    @cart = current_cart
    @credit = current_credit
  end

  def new
    @user = User.new
    @products = Product.where(wanted: 'yes')
    @cart = current_cart
    @credit = current_credit
  end

  def welcome
    @products = Product.where(stock_status:'new' ) .order(:title)
    @cart = current_cart
    @credit = current_credit

    #@orders = Order.paginate page: params[:page], order: ' created_at desc',
    #    per_page: 3

    #the following is a variation on the solution used for pagination in products
    @history = Order.paginate(:per_page => 3,
                                 :page => params[:page],
                                 :order => 'created_at DESC').where(user_id:current_user[:id])

    @traded = Trade.paginate(:per_page => 3,
                                :page => params[:page],
                                :order => 'created_at DESC').where(user_id:current_user[:id])

    #@history = Order.where(user_id:current_user[:id])
    #@traded = Trade.where(user_id:current_user[:id])
    @orders = Order.all
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  #def edit added from agile
  def edit
    @user = User.find(params[:id])
    @products = Product.where(wanted: 'yes')
    @cart = current_cart
    @credit = current_credit
  end

  #def show added from agile
  def show
    @products = Product.where(wanted: 'yes')
    @cart = current_cart
    @credit = current_credit

    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid user #{params[:id]}"
      redirect_to :controller => "store", :action => 'index', notice: 'Invalid action'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  end

  #def destroy added from agile
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def create
    @user = User.new(params[:user])
    @products = Product.where(wanted: 'yes')
    @cart = current_cart
    @credit = current_credit
    if @user.save
      redirect_to login_path, :notice => 'User creation successful!'
    else
      render :action => 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Details were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="fields">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="fields">
      <%= f.label :password %><br />
      <%= f.text_field :password %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div id="mainmargin">
  <h1>Editing User Details</h1>
     <%= render 'form' %>
<% if current_user and current_user.admin %>
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
<% else %>
    <%= link_to 'Back', :controller => "users", :action => "welcome", :notice => "Edited successfully" %>
<% end %>
</div>

app/views/users/index.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <h1>Listing Users</h1>
<table>
  <tr>
    <th>Email</th>
    <th>Admin</th>
    <th>credit</th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user)%></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
  <% end %>
</table>
<br/>
      <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div id="mainmargin">
  <h1>Join 3D or not 3D</h1>
  <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@user.errors.count, "error") %>
              prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div class="actions">
        <%= f.submit "Sign me up !"%>
      </div>
  <% end %>
  <%= link_to 'Back', products_path %>
</div>

app/views/users/show.html.erb
<div id="mainmargin">
  <p id="notice"><%= notice %></p>
  <p>
    <b>email:</b>
    <%= @user.email %>
  </p>
  <p>
    <b>Password:</b>
    <%= @user.password %>
  </p>
  <% if current_user and current_user.admin %>
      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
  <% else %>
      <%= link_to 'Back', :controller => "users", :action => "welcome", :notice => "Edited successfully" %>
  <% end %>
</div>

app/views/users/welcome.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
      <h2>Welcome Administrator</h2>
      <b><%= current_user.email %></b>
      <%=  Time.now %><br/> <br/>
     <b> We have <%= @orders.to_a.length %> orders </b>
      <br/>
      <b> We have <%= @trades.to_a.length %> trade requests </b>
  <% else %>
      <h2>Welcome to 3DorNot3D </h2>
      <b><%= current_user.email %></b>
      <br/>
      <br/>
      would you like to edit your details?
      <%= link_to 'Edit', edit_user_path(current_user) %>
      <br/>
      <br/>
      <% if current_user and not current_user.admin %>

<div id="main_left">
      <fieldset>
        <legend><h2>Your Orders</h2></legend>
          <% @history.each do |order| %>
              <b>Name:</b> <%= order.name %> <br/>
              <b>Date of purchase:</b><%= time_ago_in_words (order.created_at) %> ago <br/>
              <b>Pay type:</b><%= order.pay_type %></td> <br/>
              <%= link_to 'Order Details', order %>  <br/>  <br/>
          <% end %>
          <% if current_user and not current_user.admin %>
            <p><%= will_paginate @history %></p>
      </fieldset>
        <% end %>
</div>
      <% end %>
      <fieldset>
         <legend><h2>Your Trades</h2></legend>
            <% @traded.each do |trade| %>
            <b>Name:</b> <%= trade.name %> <br/>
            <b>Requested on:</b><%= time_ago_in_words(trade.created_at) %> ago<br/>
            <b>Status:</b><%= trade.trade_status %> <br/>

            <% if trade.trade_status == "pending"  %>
            <b>Processed on:</b> Not yet processed <br/>
                <% else %>
                <b>Processed on:</b><%= time_ago_in_words(trade.updated_at) %> ago<br/>
                <% end %>
                <%= link_to 'Trade Details', trade %>  <br/>  <br/>
            <% end %>
            <% if current_user and not current_user.admin %>
                <p><%= will_paginate @traded %></p>
         </fieldset>
          <% end %>
          <% end %>
</div>