config/routes.rb
Movies::Application.routes.draw do

  get "users/new"
  get "users/welcome"
  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :trades

  resources :credit_items

  resources :credits

  resources :users

  resources :sessions

  resources :orders

  resources :credit_items

  resources :carts

  resources :line_items

  resources :products

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  get "store/used"
  get "store/most_wanted"
  get "store/thanks"
  get "store/join"

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

   root :to => "store", :action => "index"

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items,  dependent: :destroy


  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum  { |item| item.total_price}
  end


  # 10% discount function - finds 10% value of cart if total price is €60 or more
  def promo

    if total_price >= 60.00
      total_price / 100.0 * 10.0

    else
      0.00

    end
  end

  def grand_total
      if promo
        total_price - promo
      else
        line_items.to_a.sum  { |item| item.total_price}

      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #before_filter :is_admin?
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json



  def index
    @carts = Cart.paginate page: params[:page], order: ' created_at desc',
        per_page: 10
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to :controller => "store", :action => 'index', notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, notice: "Please log in"
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])
    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id]  = nil
    respond_to do |format|
      format.html { redirect_to :controller => "store", :action => 'index', :notice => 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title"><h2>Your Cart</h2></div>
<table>
  <p id="notice"><%= notice %></p>
    <%= render(cart.line_items) %>

  <tr class="total_line">

    <td colspan="2">Sub Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>

    </tr>
  <tr class="total_line">

    <td colspan="2">Discount</td>
    <td class="total_cell"><%= number_to_currency(cart.promo) %></td>

  </tr>

  <tr class="total_line">

    <td colspan="2">You pay</td>
    <td class="total_cell"><%= number_to_currency(cart.grand_total) %></td>

  </tr>


</table>

<% if logged_in? %>
    <%= button_to "Checkout", new_order_path, method: :get %>
    <%= button_to 'Empty cart', cart, method: :delete, confirm: 'Are you sure?' %>
<% else %>
    <%= button_to "Checkout", new_order_path, method: :get %>
    <%= button_to 'Empty cart', cart, method: :delete, confirm: 'Are you sure?' %>

<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div id="mainmargin">
  <% if current_user.admin %>
  <h1>Editing cart</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @cart %> |
    <%= link_to 'Back', carts_path %>
  <% end %>
</div>

app/views/carts/index.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <h1>Listing carts</h1>
<table>
  <tr>
    <th>Value</th>
    <th>Discount</th>
    <th>Total</th>
  </tr>
<% @carts.each do |cart| %>
  <tr>
    <td><%= number_to_currency(cart.total_price) %></td>
    <td><%= number_to_currency(cart.promo) %></td>
    <td><%= number_to_currency(cart.grand_total) %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  <% end %>
</table>
<br />
  <% if current_user and current_user.admin %>
<%= link_to 'New Cart', new_cart_path %>
<p><%= will_paginate @carts %></p>
  <% end %>
    </div>

app/views/carts/new.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <h1>New cart</h1>
    <%= render 'form' %>
    <%= link_to 'Back', carts_path %>
  <% end %>
</div>

app/views/carts/show.html.erb
<div id="mainmargin">
  <% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>
      <%= render @cart %>
</div>