config/routes.rb
Movies::Application.routes.draw do

  get "users/new"
  get "users/welcome"
  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :trades

  resources :credit_items

  resources :credits

  resources :users

  resources :sessions

  resources :orders

  resources :credit_items

  resources :carts

  resources :line_items

  resources :products

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  get "store/used"
  get "store/most_wanted"
  get "store/thanks"
  get "store/join"

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

   root :to => "store", :action => "index"

  root to: 'store#index', as: 'store'

end

app/models/credit.rb
class Credit < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :credit_items, dependent: :destroy
  belongs_to :user
  belongs_to :trade

  def add_credit(product_id)
    latest_item = credit_items.find_by_product_id(product_id)
    if latest_item
      latest_item.quantity += 1
    else
      latest_item = credit_items.build(product_id: product_id)
    end
    latest_item
  end

  def credit_total
    credit_items.to_a.sum { |credit| credit.credit_total}

  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.paginate page: params[:page], order: ' created_at desc',
        per_page: 10
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credits }
    end
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
    begin
      @credit = Credit.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to :controller => "store" , :action => "index", notice: 'invalid request'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @credit }
      end
    end
  end

  # GET /credits/new
  # GET /credits/new.json
  def new
    @credit = Credit.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit }
    end
  end

  # GET /credits/1/edit
  def edit
    @credit = Credit.find(params[:id])
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(params[:credit])

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render json: @credit, status: :created, location: @credit }
      else
        format.html { render action: "new" }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credits/1
  # PUT /credits/1.json
  def update
    @credit = Credit.find(params[:id])
    respond_to do |format|
      if @credit.update_attributes(params[:credit])
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit = current_credit
    @credit.destroy
    session[:credit_id] = nil
    respond_to do |format|
      format.html { redirect_to :controller => "store", :action => "most_wanted" ,notice: 'Request has been removed' }
      format.json { head :no_content }
    end
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_credit.html.erb
<div class="cart_title"><h2>Your Credit</h2></div>
<table>
  <%= render(credit.credit_items) %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(credit.credit_total) %></td>
  </tr>
</table>
    <%= button_to "Request credit", new_trade_path, method: :get %>

    <%= button_to 'Reset', credit, method: :delete,
              confirm: 'Are you sure?' %>

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>
      <ul>
      <% @credit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<div id="mainmargin">
  <h1>Editing credit</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @credit %> |
    <%= link_to 'Back', credits_path %>
</div>

app/views/credits/index.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <h1>Listing credits</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Value</th>
    <th></th>
    <th></th>
  </tr>

<% @credits.each do |credit| %>
  <tr>
    <td><%= number_to_currency(credit.credit_total) %></td>
    <td><%= link_to 'Show', credit %></td>
    <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
    <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  <% end %>
</table>

<br />
  <% if current_user and current_user.admin %>
<%= link_to 'New Credit', new_credit_path %>
<p><%= will_paginate @credits %></p>
  <% end %>
  </div>

app/views/credits/new.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <h1>New credit</h1>
    <%= render 'form' %>
    <%= link_to 'Back', credits_path %>
  <% end %>
</div>

app/views/credits/show.html.erb
<div id="mainmargin">
  <% if current_user and current_user.admin %>
  <% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>
  <% end %>
     <%= render @credit %>
</div>